Add windows installer
sc2ad/QuestPackageManager pull request #18
Opened 2021-06-25 07:26 UTC by Lauriethefish

This PR adds a inno setup script to build an installer for Windows that adds qpm to either system or user path depending on if installing for all users or the current user only.

A github workflow has also been added to build the installer automatically. One downside of this is that inno has no direct download link for a non installer build, so a minimised setup compiler is now in the repository, alongside its license.

2021-06-27 15:35 UTC, Fernthedev approved these changes
I approve without looking at the changes because I deem it the proper way to do approvals.

2021-07-03 08:03 UTC, sc2ad requested changes
Fix version string then i approb

2021-07-03 08:04 UTC, Lauriethefish commented
Version feexed

2021-07-03 08:58 UTC, sc2ad approved these changes

2021-07-03 08:59 UTC, merged